apiVersion: v1
kind: Pod
metadata: 
  name: nginx
spec:
  containers:
  # EQUIVALENT ---> docker run -d --name nginx nginx:v1 .
  - name: nginx
    image: nginx
  # nodeSelector:
  #   hardware: gpu
  tolerations:
  - key: "hardware"
    operator: "Equal"
    value: "gpu"
    effect: "NoSchedule"  