apiVersion: v1
kind: Pod
metadata: 
  name: nginx
spec:
  affinity:
    nodeAffinity:
    # Soft rule
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: another-node-label-key
            operator: In
            values:
            - another-node-label-value  
  containers:
  # EQUIVALENT ---> docker run -d --name nginx nginx:v1 .
  - name: nginx
    image: nginx
  # nodeSelector:
  #   hardware: gpu
  tolerations:
  - key: "hardware"
    operator: "Equal"
    value: "gpu"
    effect: "NoSchedule"  