apiVersion: v1
kind: Pod
metadata: 
  name: pod-1
  labels:
    purpose: affinity
spec:
  containers:
  # EQUIVALENT ---> docker run -d --name nginx nginx:v1 .
  - name: nginx
    image: nginx:stable-perl
---
apiVersion: v1
kind: Pod
metadata: 
  name: pod-2
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:   # Hard Rule
      - labelSelector:
          matchExpressions:
          - key: purpose
            operator: In
            values:
            - pod-1
        topologyKey: topology.kubernetes.io/zone
  containers:
  # EQUIVALENT ---> docker run -d --name nginx nginx:v1 .
  - name: nginx
    image: nginx:stable-perl
  tolerations:
  - key: "hardware